---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    

  - name: Install The Apache 2 Package
    apt:
      name: a
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution = "Ubuntu"

