---

- hosts: all
  become: true
  tasks:

##    

  - name: Install The Apache2 Package,libapache2-mod-php and update the cache
    apt:
      name: a
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

    when: ansible_distribution = "Ubuntu"

## Can Set up variables and store them in the inventory
# Using the "package" module helps run the package manage for the various distro
  # - name: Install The Apache2 Package, libapache2-mod-php and update the cache
  #   package:
  #     name: a
  #       - "{{apache_package}}"
  #       - "{{php_package}}"
  #     state: latest
  #     update_cache: yes

